name: performance-tests-macro
permissions:
  contents: read

on:
  push:
    branches:
      - "main" # or "master"
    paths-ignore:
      - "**/*.md"
  pull_request:
  workflow_dispatch:

env:
  TELEMETRY_ENABLED: false
  NODE_OPTIONS: "--max_old_space_size=8192"
  PR_TITLE: ${{ github.event.pull_request.title }}
  APP_HARNESS_HEADLESS: 1
  PYTHONUNBUFFERED: 1

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    # runs-on: codspeed-macro-staging
    env:
      CODSPEED_LOG: debug
   
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Find python version used by uv
        run: | 
          which -a python
          which -a python3
          uv run which pytest
          uv run which python
          uv run python -c "import sysconfig; print('/'.join(sysconfig.get_config_vars('LIBDIR', 'INSTSONAME')))"
          python3 -c "import sysconfig; print('/'.join(sysconfig.get_config_vars('LIBDIR', 'INSTSONAME')))"

          ls -alh .venv/bin/
          ls -alh .venv/lib/python3.13/
          cat .venv/bin/pytest

      - uses: moonrepo/setup-rust@v1
        with:
          channel: '1.88.0'

      - name: Install runner from git
        run: cargo install --git https://github.com/CodSpeedHQ/runner.git --branch cod-1315-statically-linked-libpythonso-adds-extra-frames-to-valgrind

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Run benchmarks
        run: codspeed run --api-url https://gql.staging.preview.codspeed.io/ --upload-url https://api.staging.preview.codspeed.io/upload -- uv run pytest tests/benchmarks --codspeed
        env:
          CODSPEED_LOG: debug
          CODSPEED_RUNNER_MODE: "instrumentation"
          CODSPEED_TOKEN: ${{ secrets.CODSPEED_TOKEN }}

      # - name: Run benchmarks
      #   uses: CodSpeedHQ/action@v4
      #   env:
      #     CODSPEED_LOG: debug
      #     CODSPEED_PERF_ENABLED: true
      #   with:
      #     token: ${{ secrets.CODSPEED_TOKEN }}
      #     mode: walltime
      #     run: uv run pytest tests/benchmarks --codspeed
      #     upload-url: https://api.staging.preview.codspeed.io/upload
